#ifndef _LPMS_E1_H_
#define _LPMS_E1_H_

#include "stm32f4xx_hal.h"

HAL_StatusTypeDef LPMS_ME1_Init(I2C_HandleTypeDef *);
HAL_StatusTypeDef LPMS_ME1_GetEuler(I2C_HandleTypeDef *, float *);

#define LPMS_ME1_I2C_TIMEOUT 100
// by default it works in MOD0=1 MOD=1 (I2C ADD0=1) 
#define LPMS_ME1_I2C_ADRRESS  0x64

typedef union {
    uint8_t u8vals[4];
    uint32_t u32val;
    float fval;
} LPMS_ME1_DataDecoder;


/*
  *System Registers{
  */
#define LPMS_ME1_ALL_REG_SIZE  128
#define LPMS_ME1_DATA_SIZE 84

#define FUN_CONFIG   0x00
#define SYS_CONFIG   0x01
#define DATA_CTRL     0x02
#define DATA_ENABLE   0x03
#define CTRL_0_A     0x04
#define CTRL_1_G      0x05
#define CTRL_2_M      0x06
#define STATUS    0x07
#define FILTER_CONFIG     0x08
#define UART_CONFIG  0x09

#define LPMS_ME1_DATA_BASE 0x20 //Data register start address d32

//Data Register
#define LPMS_ME1_TIMESTAMP_0 (LPMS_ME1_DATA_BASE + 0)
#define LPMS_ME1_TIMESTAMP_1 (LPMS_ME1_DATA_BASE + 1)
#define LPMS_ME1_TIMESTAMP_2 (LPMS_ME1_DATA_BASE + 2)
#define LPMS_ME1_TIMESTAMP_3 (LPMS_ME1_DATA_BASE + 3)
#define LPMS_ME1_ACC_X_0 (LPMS_ME1_DATA_BASE + 4)
#define LPMS_ME1_ACC_X_1 (LPMS_ME1_DATA_BASE + 5)
#define LPMS_ME1_ACC_X_2 (LPMS_ME1_DATA_BASE + 6)
#define LPMS_ME1_ACC_X_3 (LPMS_ME1_DATA_BASE + 7)
#define LPMS_ME1_ACC_Y_0 (LPMS_ME1_DATA_BASE + 8)
#define LPMS_ME1_ACC_Y_1 (LPMS_ME1_DATA_BASE + 9)
#define LPMS_ME1_ACC_Y_2 (LPMS_ME1_DATA_BASE + 10)
#define LPMS_ME1_ACC_Y_3 (LPMS_ME1_DATA_BASE + 11)
#define LPMS_ME1_ACC_Z_0 (LPMS_ME1_DATA_BASE + 12)
#define LPMS_ME1_ACC_Z_1 (LPMS_ME1_DATA_BASE + 13)
#define LPMS_ME1_ACC_Z_2 (LPMS_ME1_DATA_BASE + 14)
#define LPMS_ME1_ACC_Z_3 (LPMS_ME1_DATA_BASE + 15)
#define LPMS_ME1_GYR_X_0 (LPMS_ME1_DATA_BASE + 16)
#define LPMS_ME1_GYR_X_1 (LPMS_ME1_DATA_BASE + 17)
#define LPMS_ME1_GYR_X_2 (LPMS_ME1_DATA_BASE + 18)
#define LPMS_ME1_GYR_X_3 (LPMS_ME1_DATA_BASE + 19)
#define LPMS_ME1_GYR_Y_0 (LPMS_ME1_DATA_BASE + 20)
#define LPMS_ME1_GYR_Y_1 (LPMS_ME1_DATA_BASE + 21)
#define LPMS_ME1_GYR_Y_2 (LPMS_ME1_DATA_BASE + 22)
#define LPMS_ME1_GYR_Y_3 (LPMS_ME1_DATA_BASE + 23)
#define LPMS_ME1_GYR_Z_0 (LPMS_ME1_DATA_BASE + 24)
#define LPMS_ME1_GYR_Z_1 (LPMS_ME1_DATA_BASE + 25)
#define LPMS_ME1_GYR_Z_2 (LPMS_ME1_DATA_BASE + 26)
#define LPMS_ME1_GYR_Z_3 (LPMS_ME1_DATA_BASE + 27)
#define LPMS_ME1_MAG_X_0 (LPMS_ME1_DATA_BASE + 28)
#define LPMS_ME1_MAG_X_1 (LPMS_ME1_DATA_BASE + 29)
#define LPMS_ME1_MAG_X_2 (LPMS_ME1_DATA_BASE + 30)
#define LPMS_ME1_MAG_X_3 (LPMS_ME1_DATA_BASE + 31)
#define LPMS_ME1_MAG_Y_0 (LPMS_ME1_DATA_BASE + 32)
#define LPMS_ME1_MAG_Y_1 (LPMS_ME1_DATA_BASE + 33)
#define LPMS_ME1_MAG_Y_2 (LPMS_ME1_DATA_BASE + 34)
#define LPMS_ME1_MAG_Y_3 (LPMS_ME1_DATA_BASE + 35)
#define LPMS_ME1_MAG_Z_0 (LPMS_ME1_DATA_BASE + 36)
#define LPMS_ME1_MAG_Z_1 (LPMS_ME1_DATA_BASE + 37)
#define LPMS_ME1_MAG_Z_2 (LPMS_ME1_DATA_BASE + 38)
#define LPMS_ME1_MAG_Z_3 (LPMS_ME1_DATA_BASE + 39)
#define LPMS_ME1_EULER_X_0   (LPMS_ME1_DATA_BASE + 40)
#define LPMS_ME1_EULER_X_1   (LPMS_ME1_DATA_BASE + 41)
#define LPMS_ME1_EULER_X_2   (LPMS_ME1_DATA_BASE + 42)
#define LPMS_ME1_EULER_X_3   (LPMS_ME1_DATA_BASE + 43)
#define LPMS_ME1_EULER_Y_0   (LPMS_ME1_DATA_BASE + 44)
#define LPMS_ME1_EULER_Y_1   (LPMS_ME1_DATA_BASE + 45)
#define LPMS_ME1_EULER_Y_2   (LPMS_ME1_DATA_BASE + 46)
#define LPMS_ME1_EULER_Y_3   (LPMS_ME1_DATA_BASE + 47)
#define EULER_Z_0   (LPMS_ME1_DATA_BASE + 48)
#define EULER_Z_1   (LPMS_ME1_DATA_BASE + 49)
#define EULER_Z_2   (LPMS_ME1_DATA_BASE + 50)
#define EULER_Z_3   (LPMS_ME1_DATA_BASE + 51)
#define QUAT_W_0    (LPMS_ME1_DATA_BASE + 52)
#define QUAT_W_1    (LPMS_ME1_DATA_BASE + 53)
#define QUAT_W_2    (LPMS_ME1_DATA_BASE + 54)
#define QUAT_W_3    (LPMS_ME1_DATA_BASE + 55)
#define QUAT_X_0    (LPMS_ME1_DATA_BASE + 56)
#define QUAT_X_1    (LPMS_ME1_DATA_BASE + 57)
#define QUAT_X_2    (LPMS_ME1_DATA_BASE + 58)
#define QUAT_X_3    (LPMS_ME1_DATA_BASE + 59)
#define QUAT_Y_0    (LPMS_ME1_DATA_BASE + 60)
#define QUAT_Y_1    (LPMS_ME1_DATA_BASE + 61)
#define QUAT_Y_2    (LPMS_ME1_DATA_BASE + 62)
#define QUAT_Y_3    (LPMS_ME1_DATA_BASE + 63)
#define QUAT_Z_0    (LPMS_ME1_DATA_BASE + 64)
#define QUAT_Z_1    (LPMS_ME1_DATA_BASE + 65)
#define QUAT_Z_2    (LPMS_ME1_DATA_BASE + 66)
#define QUAT_Z_3    (LPMS_ME1_DATA_BASE + 67)
#define LIN_ACC_X_0 (LPMS_ME1_DATA_BASE + 68)
#define LIN_ACC_X_1 (LPMS_ME1_DATA_BASE + 69)
#define LIN_ACC_X_2 (LPMS_ME1_DATA_BASE + 70)
#define LIN_ACC_X_3 (LPMS_ME1_DATA_BASE + 71)
#define LIN_ACC_Y_0 (LPMS_ME1_DATA_BASE + 72)
#define LIN_ACC_Y_1 (LPMS_ME1_DATA_BASE + 73)
#define LIN_ACC_Y_2 (LPMS_ME1_DATA_BASE + 74)
#define LIN_ACC_Y_3 (LPMS_ME1_DATA_BASE + 75)
#define LIN_ACC_Z_0 (LPMS_ME1_DATA_BASE + 76)
#define LIN_ACC_Z_1 (LPMS_ME1_DATA_BASE + 77)
#define LIN_ACC_Z_2 (LPMS_ME1_DATA_BASE + 78)
#define LIN_ACC_Z_3 (LPMS_ME1_DATA_BASE + 79)
#define LPMS_ME1_TEMP_0  (LPMS_ME1_DATA_BASE + 80)
#define LPMS_ME1_TEMP_1  (LPMS_ME1_DATA_BASE + 81)
#define LPMS_ME1_TEMP_2  (LPMS_ME1_DATA_BASE + 82)
#define LPMS_ME1_TEMP_3  (LPMS_ME1_DATA_BASE + 83)
#define LPMS_ME1_WAI  (LPMS_ME1_DATA_BASE + 84) // 0x74

/*
  *}System Registers
  */
 
#endif // _LPMS_E1_H_
